### ISSUE TITLE
Web workers or use assembly threads?

### ISSUE THREAD

**Issue by marksyzm** [etercast/mp3#2]
Firstly, excellent work! It's the only solid MP3 encoder I've found on NPM so far; lamejs has many issues with its unusual sample rates and seems pretty unusable in terms of the code it chucks out on modern platforms. 
I'm currently implementing your encoder as a real time encoder via StencilJS on a mobile app and was wondering if you knew if this supports multi-threaded encoding "out of the box" seeing as it uses Web Assembly via Emscripten? Otherwise shall I stick to using web workers?
Apologies for the general question used here as an issue but there's not really any other way to ask in

**Comment by AzazelN28** [comment]
Thank you very much! ^_^

And about your question: yes, it supports multi-threaded encoding, you can instantiate as much encoders as you need in different threads using Web Workers. In fact, it should be very easy to copy the README example inside a worker and use it with something like worker-loader (the webpack loader).

**Comment by marksyzm** [comment]
Ah, not quite what I meant :) In web assembly you can create multi-threads without having to create a web worker! See here:
https://blog.scottlogic.com/2019/07/15/multithreaded-webassembly.html

**Comment by AzazelN28** [comment]
Thanks, I didn't know about this! We're currently working on other things that have greater priority but I'll try to allocate some time to work on this. Thanks!
